character:
  race: Troll
  player_class: Mage
  spells:
    mage_spells_to_use:
      - 38697 #Frostbolt rank14
      - 38692 #Fireball rank14
      - 116
  gear:
    0:            #ammo
    1: 23032           #head
    2:            #neck
    3: 22983           #shoulder
    4:            #body (shirt)
    5: 1716           #chest
    6:            #waist (belt)
    7:            #legs
    8:            #feet
    9:            #wrist
    10:           #hand
    11:           #finger1
    12:           #finger2
    13:           #trinket1
    14:           #trinket2
    15:           #back
    16:           #mainhand
    17:           #offhand
    18:           #ranged
    19:           #tabard
  talents:
    - 12577
    - 12341
    - 31660
    - 16766
    - 11124
    #- 11129
enemy:
  boss: Yes
  level: 73
  attributes:
    armor: 0
    holy_resistance: 0
    frost_resistance: 0
    fire_resistance: 0
    nature_resistance: 0
    arcane_resistance: 0
    shadow_resistance: 0
sim:
  sim_type: dps
  duration: 20