character:
  race: Troll
  player_class: Mage
  spells:
    mage_spells_to_use:
      - 38697 #Frostbolt rank14
      - 38692 #Fireball rank14
      - 116
  gear:
    0:            #ammo
    1: 24266           #head
    2:            #neck
    3: 22983           #shoulder
    4:            #body (shirt)
    5: 1716           #chest
    6:            #waist (belt)
    7: 24262           #legs
    8:            #feet
    9:            #wrist
    10:           #hand
    11:           #finger1
    12:           #finger2
    13:           #trinket1
    14:           #trinket2
    15:           #back
    16:           #mainhand
    17:           #offhand
    18: 22821          #ranged
    19:           #tabard
  talents:
    talent_calc_link: "https://legacy-wow.com/tbc-talents/mage-talents/?tal=2302250000000000000000050520200230333005312500030000000000000000000" #fire
    #talent_calc_link: "https://legacy-wow.com/tbc-talents/mage-talents/?tal=2300050000000000000000000000000000000000000000535323310033010251551"  #frost
    talent_list:
enemy:
  boss: Yes
  level: 73
  attributes:
    armor: 0
    holy_resistance: 0
    frost_resistance: 0
    fire_resistance: 0
    nature_resistance: 0
    arcane_resistance: 0
    shadow_resistance: 0
sim:
  sim_type: dps
  duration: 30